Repository conduktor/terraform-provider-conduktor, pull requests merged in 2025-08, with the labels that each got.

#110 Fix acceptance tests CI
  .github/workflows/test.yml
  internal/provider/console_connector_v2_resource_test.go
  internal/provider/console_partner_zone_v2_resource_test.go
  internal/test/test_helpers.go
Labels: bug, chore

#109 Update topic RegEX in provider_code_spec.json
  internal/provider/console_topic_v2_resource_test.go
  internal/schema/resource_console_topic_v2/console_topic_v2_resource_gen.go
  internal/testdata/console/topic_v2/resource_create.tf
  internal/testdata/console/topic_v2/resource_update.tf
  provider_code_spec.json
Labels: bug

#112 Fix empty license ci tests
  .github/workflows/test.yml
Labels: chore

#117 Fix partnerzone tests
  .github/workflows/test.yml
  GNUmakefile
  docker-compose.yaml
  docs/resources/console_partner_zone_v2.md
  examples/resources/conduktor_console_partner_zone_v2/complex.tf
  internal/provider/console_partner_zone_v2_resource_test.go
  internal/testdata/console/partner_zone_v2/resource_create.tf
  internal/testdata/console/partner_zone_v2/resource_minimal.tf
  internal/testdata/console/partner_zone_v2/resource_update.tf
  testdata/init/init_console.yaml
  testdata/init/init_gateway.yaml
Labels: bug

#118 Split Connector example tests to prevent KafkaConnect error
  internal/provider/console_connector_v2_resource_test.go
Labels: bug
