Repository conduktor/terraform-provider-conduktor, pull requests merged in 2025-05, with the labels that each got.

#78 Fix/permissions ksqldb
  docs/resources/console_group_v2.md
  docs/resources/console_user_v2.md
  examples/resources/conduktor_console_user_v2/complex.tf
  internal/model/permissions.go
  internal/provider/console_user_v2_resource_test.go
  internal/schema/resource_console_group_v2/console_group_v2_resource_gen.go
  internal/schema/resource_console_user_v2/console_user_v2_resource_gen.go
  internal/schema/schema_utils.go
  provider_code_spec.json
Labels: bug

#80 Update local test environment and CI test matrix
  .env
  .github/workflows/test.yml
  docker-compose.yaml
  scripts/wait_for_test_env_ready.sh
Labels: bug, chore

#82 chore: adding gateway image print to initial startup script
  scripts/start_test_env.sh
Labels: chore

#83 Update console platform and permissions
  .env
  .github/workflows/test.yml
  internal/schema/validation/schema_validation.go
Labels: enhancement, dependencies

#86 Update dependencies to fix missing GetResourceIdentitySchemas error with terraform 1.12.1
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: bug, dependencies
